CREATE TABLE `E_BOOK` (
    `CALLNO` VARCHAR(255), 
    `NAME` VARCHAR(255),   
    `AUTHOR` VARCHAR(255), 
    `PUBLISHER` VARCHAR(255), 
    `QUANTITY` INT,
    `ISSUED` INT,
    PRIMARY KEY (`CALLNO`)
);

CREATE TABLE `E_LIBRARIAN` (
    `ID` INT AUTO_INCREMENT,
    `NAME` VARCHAR(255),
    `PASSWORD` VARCHAR(255),
    `EMAIL` VARCHAR(255),
    `MOBILE` INT,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `E_ISSUEBOOK` (
    `CALLNO` VARCHAR(255) NOT NULL,
    `STUDENTID` VARCHAR(255) NOT NULL,
    `STUDENTNAME` VARCHAR(255),
    `STUDENTMOBILE` INT,
    `ISSUEDDATE` DATE,
    `RETURNSTATUS` TEXT
);
